Document: gcc-arm-linux-androideabi
Title: Debian gcc-arm-linux-androideabi Manual
Author: <insert document author here>
Abstract: This manual describes what gcc-arm-linux-androideabi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gcc-arm-linux-androideabi/gcc-arm-linux-androideabi.sgml.gz

Format: postscript
Files: /usr/share/doc/gcc-arm-linux-androideabi/gcc-arm-linux-androideabi.ps.gz

Format: text
Files: /usr/share/doc/gcc-arm-linux-androideabi/gcc-arm-linux-androideabi.text.gz

Format: HTML
Index: /usr/share/doc/gcc-arm-linux-androideabi/html/index.html
Files: /usr/share/doc/gcc-arm-linux-androideabi/html/*.html
